name: test-self-hosted

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test1
        run: echo {{ vars.APP_MODE }}

      - name: test2
        run: echo {{ vars.SUPPORT_EMAIL }}

      - name: test3
        run: echo {{ secrets.SUPPORT_EMAIL }}
