name: test-self-hosted

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: test1
        run: uname -a

      - name: test2
        run: sudo apt install openjdk-21-jdk
